services:
  frontend:
    restart: always
    build:
      context: frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  
  backend:
    restart: always
    build:
      context: backend
    ports:
      - 5000:5000
    environment:
      NODE_ENV: development
      DATABASE_URL: postgres://postgres:ayylmao123@db:5432/perntodo
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    restart: always
    image: postgres
    environment:
      POSTGRES_PASSWORD: ayylmao123
      POSTGRES_USER: postgres
      POSTGRES_DB: perntodo
      PGDATA: /data/postgres
    # port goes from local port:docker port
    ports:
      - '13000:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/database.sql:/docker-entrypoint-initdb.d/database.sql
